### ISSUE TITLE
bug(authentication): Default FirebaseApp is not initialized

### ISSUE THREAD

**Issue by jmondragon** [robingenz/capacitor-firebase#24]
**Plugin version:**
0.4.3

**Platform(s):**
Android, iOS

**Current behavior:**
After installing the plugin and performing npx cap sync, when trying to run the application in Android Studio it crashes with the following error in the logs:
`Default FirebaseApp is not initialized in this process com.example.myapp. Make sure to call FirebaseApp.initializeApp(Context) first.`

I have been following the example from your demo app and have included the initialization in the constructor of my `app.component.ts`.  I even copied your FirebaseAuthenticationService (and basically the whole "core" folder) to try to get as close as I could to your demo.

It gives a similar error in XCode with the emulator, but doesn't crash (but also doesn't authentication for either Google or Facebook).  Other methods seem to at least fire up the browser window, though I don't have them enabled in Firebase.

**Expected behavior:**
Expect the app to not crash on load and to authenticate users via Google.

**Steps to reproduce:**
In my instance, I simply installed the plugin into an existing project and ran `npx cap sync`.

**Related code:**
From `app.component.ts`:
```
  constructor(
    private readonly firebaseAuthenticationService: FirebaseAuthenticationService
  ) {
    this.initializeApp();
  }
  private async initializeApp(): Promise<void> {
    await this.firebaseAuthenticationService.initialize();
  }
```

**Other information:**
None

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3

[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
I have moved this issue to a new repository.

**Comment by aliexalter** [comment]
On Android I am having same issue. 
Minimum to reproduce this error is 
```
npm install @capacitor-firebase/authentication firebase
npx cap sync
```
After that open android studio bumble bee run the app on device via USB. 
The following error will show up


```
03/30 18:34:12: Launching 'app' on Google Pixel XL.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.myapp.id/com.myapp.id.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7727 on device 'google-pixel_xl-HT6A40201259'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/com.myapp.i: Late-enabling -Xcheck:jni
E/com.myapp.i: Unknown bits set in runtime_flags: 0x8000

W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.

I/FirebaseInitProvider: FirebaseApp initialization unsuccessful

E/com.myapp.i: Invalid ID 0x00000000.
W/com.myapp.i: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/com.memories.i: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/WebViewFactory: Loading com.google.android.webview version 99.0.4844.73 (code 484407333)
W/com.myapp.i: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/com.myapp.i: Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/com.myapp.i: Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/com.myapp.i: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/com.myapp.i: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider: Loaded version=99.0.4844.73 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
E/com.myapp.i: Invalid ID 0x00000000.
E/com.myapp.i: Invalid ID 0x00000000.
I/cr_LibraryLoader: Successfully loaded native library
I/cr_CachingUmaRecorder: Flushed 9 samples from 9 histograms.
D/Capacitor: Starting BridgeActivity
D/Capacitor: Registering plugin: WebView

D/Capacitor: Registering plugin: FirebaseAuthentication
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.id, PID: 7727
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.myapp.id. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
        at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.0.1:1)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:53)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:26)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458)
        at com.getcapacitor.Bridge.<init>(Bridge.java:188)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=0 bindings:WM  
E/cr_PlatformSer-Internal: UsageReporting query failed
```

**Comment by robingenz** [comment]
> Minimum to reproduce this error is
> npm install @capacitor-firebase/authentication firebase
> npx cap sync

Here are missing important setup steps described in: https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/README.md#installation.

Please follow the steps exactly and try again. Make sure that you have added the google-service.json file.
