### ISSUE TITLE
bug: app crashes `java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.signin.GoogleSignIn"`

### ISSUE THREAD

**Issue by mesqueeb** [robingenz/capacitor-firebase#60]
**Plugin(s):**

- `"@robingenz/capacitor-firebase-authentication": "^0.4.0",`

I should upgrade to this, but haven't done yet. However, since today, not sure what went wrong, but I cannot launch on android anymore.

I found this error log:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.colorfulcast.beta, PID: 11454
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignIn;
        at dev.robingenz.capacitorjs.plugins.firebase.auth.handlers.GoogleAuthProviderHandler.<init>(GoogleAuthProviderHandler.java:30)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:272)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication.<init>(FirebaseAuthentication.java:52)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:25)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458)
        at com.getcapacitor.Bridge.<init>(Bridge.java:188)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2968)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.signin.GoogleSignIn" on path: DexPathList[[zip file "/data/app/com.colorfulcast.beta-nio1AIK37LpTmCyQWjWt4w==/base.apk"],nativeLibraryDirectories=[/data/app/com.colorfulcast.beta-nio1AIK37LpTmCyQWjWt4w==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.handlers.GoogleAuthProviderHandler.<init>(GoogleAuthProviderHandler.java:30) 
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:272) 
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication.<init>(FirebaseAuthentication.java:52) 
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:25) 
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95) 
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59) 
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503) 
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458) 
        at com.getcapacitor.Bridge.<init>(Bridge.java:188) 
        at com.getcapacitor.Bridge.<init>(Bridge.java:65) 
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288) 
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72) 
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391) 
        at android.app.Activity.performStart(Activity.java:7157) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2968) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6702) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
```

**Platform(s):**

- android only

**Current behavior:**
 
- the app crashes right after launch. don't even see splash

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3
```

**Comment by mesqueeb** [comment]
another computer & android gave me this:
```
    --------- beginning of crash
2022-04-04 11:57:31.076 17453-17453/com.colorfulcast.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.colorfulcast.beta, PID: 17453
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignIn;
        at dev.robingenz.capacitorjs.plugins.firebase.auth.handlers.GoogleAuthProviderHandler.<init>(GoogleAuthProviderHandler.java:30)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:272)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthentication.<init>(FirebaseAuthentication.java:52)
        at dev.robingenz.capacitorjs.plugins.firebase.auth.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:25)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458)
        at com.getcapacitor.Bridge.<init>(Bridge.java:188)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
```
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/3253920/161466908-995fe283-63d1-42a4-a897-4dda530d1515.png">

**Comment by mesqueeb** [comment]
upgraded to latest versions.
figured out this was missing:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/3253920/161468545-0dec09be-afe3-4211-ac90-884f8ba9b796.png">
