### ISSUE TITLE
bug: Calling FirebaseAuthentication.getIdToken() before auth'd causes fatal error & app crashes

### ISSUE THREAD

**Issue by lincolnthree** [robingenz/capacitor-firebase#64]
**Plugin(s):**

authentication 0.21

**Platform(s):**

Android

**Current behavior:**

call `FirebaseAuthentication.getIdToken()` from the JS client before an ID token exists in the Native cache.

```
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseUser.getIdToken(boolean)' on a null object reference
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.getIdToken(FirebaseAuthentication.java:79)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.getIdToken(FirebaseAuthenticationPlugin.java:43)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.maritlabs.topdecked.mtg, PID: 17988
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:601)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:592)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseUser.getIdToken(boolean)' on a null object reference
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.getIdToken(FirebaseAuthentication.java:79)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.getIdToken(FirebaseAuthenticationPlugin.java:43)
```

**Expected behavior:**

Don't crash :) Just return null.

**Steps to reproduce:**

1. Install a fresh build of an app.
2. Don't authenticate.
3. Call `FirebaseAuthentication.getIdToken()`

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
mshark:topdecked-unified lincoln$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/ios: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/core: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
mshark:topdecked-unified lincoln$ 
```

**Comment by robingenz** [comment]
Hey @lincolnthree,
you are right, it should return null.

You can use the following as temporary workaround:

```ts
const getIdToken = async () => {
  const { user } = await FirebaseAuthentication.getCurrentUser();
  if (!user) {
    return null;
  }
  const { token } = await FirebaseAuthentication.getIdToken();
  return token;
};
```

**Comment by lincolnthree** [comment]
Excellent. Thanks for confirming. That's the workaround I ended up with as well :) PS. Thanks for this fantastic library. A bit more complex to set up than previous alternatives, but VERY nicely done.

**Comment by robingenz** [comment]
@lincolnthree Thank you for these kind words. If you have any ideas on how to make the setup easier, feel free to let me know. I am always happy about ideas and tips. (best in a new issue, a discussion or by mail)

**Comment by travisBradfield** [comment]
Hello, this was very helpful. I'm a bit confused though. When does the _currentUser_ get set? I'm doing a firebase login with email, then doing the firebase verify email. To check if the email has been verified i call the `await FirebaseAuthentication.getIdToken()`. I was then running into the same error as @lincolnthree . I've resolved it based on your recommendation. However, now when I call the new `getIdToken()` method, I'm getting a null. How come the user isn't yet set? Thanks!

**Comment by robingenz** [comment]
> Hello, this was very helpful. I'm a bit confused though. When does the _currentUser_ get set? I'm doing a firebase login with email, then doing the firebase verify email. To check if the email has been verified i call the `await FirebaseAuthentication.getIdToken()`. I was then running into the same error as @lincolnthree . I've resolved it based on your recommendation. However, now when I call the new `getIdToken()` method, I'm getting a null. How come the user isn't yet set? Thanks!

`currentUser` is set as soon as a user logs in via one of the signIn methods of the plugin. Since the plugin does not yet support password authentication (see #27), I assume you are using the Firebase JS SDK directly. If that is the case, then you are only logging the user in on the web layer and not on the native layer. This results in the currentUser not being set on native devices, as the plugin does not know it.
