### ISSUE TITLE
bug: Failed resolution of: Lcom/facebook/CallbackManager

### ISSUE THREAD

**Issue by zawmn** [robingenz/capacitor-firebase#82]
**Plugin(s):**

"@capacitor-firebase/authentication": "^0.2.2",
"firebase": "^9.8.1",

**Platform(s):**

Android, ionic, angular

**Current behavior:**

I'm using the authentication plugin only for FirebaseAuthentication.signInWithPhoneNumber.
I also only choose phone in providers in capacitor.config.json
"FirebaseAuthentication": {
			"skipNativeAuth": false,
			"providers": ["phone"]
		},
My code is working well in ios, but when I try to run it in Android, I got below error message and the app is close automatically when start. 
I didn't use or call any facebook method in my project.

`
2022-05-11 18:03:48.534 26307-26307/? D/Capacitor: Registering plugin: FirebaseAuthentication
2022-05-11 18:03:48.546 26307-26307/? D/AndroidRuntime: Shutting down VM
2022-05-11 18:03:48.548 26307-26307/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxx.xxxxxx, PID: xxxxxx
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/CallbackManager$Factory;
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.FacebookAuthProviderHandler.<init>(FacebookAuthProviderHandler.java:30)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:389)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:51)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:38)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)`

**Expected behavior:**

The application should be able to run.

**Steps to reproduce:**

Install the package, npm i @capacitor-firebase/authentication
Then setup for phone authentication only. 

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
Capacitor Doctor

Latest Dependencies:       

  @capacitor/cli: 3.5.1    
  @capacitor/core: 3.5.1   
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1    

Installed Dependencies:    

  @capacitor/cli: 3.4.3    
  @capacitor/core: 3.4.3   
  @capacitor/ios: 3.4.3    
  @capacitor/android: 3.5.0

[success] Android looking great! 👌
[error] Xcode is not installed
```

**Comment by robingenz** [comment]
Hi @zawmn,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by zawmn** [comment]
Hello

This is my fault.  I didn't read the the example code well. 

Previously I added below code only in capacitor.config.json. 
  plugins: {
    FirebaseAuthentication: {
      skipNativeAuth: false,
      providers: ["phone"],
    },
  },

When I added this code also in capacitor.config.ts, the error is gone. 

Thanks
